SketchUpPro/SketchUpPro.munki.recipe
Per autopkg/jps3-recipes#5 move to a copy_from_dmg rather than a .pkg Munki package. This is so that folks who don't run an autopkgserver can still use the recipe. Also included are some minor tweaks to the pkginfo keys.
=> SketchUp munki copy_from_dmg recipe

SketchUpPro/SketchUpPro.munki.recipe
Now that we've split off the Munki recipe from the .pkg recipe, we need to separately verify signatures.
=> Check signatures in Munki recipe

OpenSCAD/OpenSCAD.download.recipe
Added a note that code signature verification isn't going to happen for OpenSCAD:
```
codesign --display -r- --deep -v /Applications/OpenSCAD.app 
/Applications/OpenSCAD.app: code object is not signed at all
```
=> Code sig ver note for OpenSCAD

SketchUpPro/SketchUpPro.download.recipe
I realize this may impact people who promote to production without
testing, but as it stands a RELEASE_YEAR of 2016 causes the SketchUpPro
recipes to currently fail.
=> Changing RELEASE_YEAR to 2017

Objective-See/OverSight.download.recipe, Objective-See/OverSight.munki.recipe
It was missing 😊
- Download and un-pack
- Import only the Application into Munki (skip the "installer")
Note: I did not add any script to auto launch like the installer do. If needed, end user can add postscript to overwrite
=> Added recipe for OverSight

VueScan/VueScan.munki.recipe
Removed CodeSignatureVerifier for two reasons:
1) Using 'expected_authority_names' to verify .app bundles is deprecated and may be removed in a future AutoPkg release.
2) Parent download recipe (com.github.hansen-m.download.VueScan) now includes CodeSignatureVerifier using the current 'requirement' argument to verify .app bundles; a second, redundant CodeSignatureVerifier process in the VueScan.munki recipe is not needed.
=> Removed CodeSignatureVerifier from VueScan.munki.recipe.

VueScan/VueScan.pkg.recipe
Using `expected_authority_names` with .app bundles is no longer supported in AutoPkg 1.0.3.
=> Replaced expected_authority_names with requirement string

InVesalius/InVesalius.munki.recipe
`plutil -lint` fails without the array close tag.
=> Restore missing array close tag

Objective-See/BlockBlock.download.recipe, Objective-See/DHS.download.recipe, Objective-See/KextViewr.download.recipe, Objective-See/KnockKnock.download.recipe, Objective-See/Lockdown.download.recipe, Objective-See/Ostiarius.download.recipe, Objective-See/OverSight.download.recipe, Objective-See/TaskExplorer.download.recipe, Objective-See/WhatsYourSign.download.recipe
Added `--compress` curl option to fix URLTextSearcher errors and enabled strict code signature verification for a number of Objective-See download recipes.
=> Objective-See recipe fixes

Cura/cura-lulzbot.download.recipe
This PR updates the re pattern for the Cura lulzbot edition download recipe to reference the new hosting domain `alephobjects.com`.
=> Update re pattern for Cura Lulzbot

Arduino/Arduino.download.recipe, Arduino/Arduino.pkg.recipe, BetterZip/BetterZip.download.recipe, Cura/cura-lulzbot.munki.recipe, Fritzing/Fritzing.pkg.recipe, OpenSCAD/OpenSCAD.pkg.recipe, Pashua/Pashua.munki.recipe, Pashua/Pashua.pkg.recipe, Scout-App/Scout-App.munki.recipe, Slic3r/Slic3r.download.recipe, Soulver/Soulver.munki.recipe, TotalTerminal/TotalTerminal.munki.recipe, VueScan/VueScan.munki.recipe, VueScan/VueScan.pkg.recipe, X-Rite/i1Diagnostics.download.recipe, X-Rite/i1Diagnostics.munki.recipe, fseventer/fseventer.download.recipe, fseventer/fseventer.munki.recipe, fseventer/fseventer.pkg.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
=> Remove NAME variable from app paths

PathFinder/PackageInfoTemplate, PathFinder/PathFinder.download.recipe, PathFinder/PathFinder.munki.recipe, PathFinder/PathFinder.pkg.recipe, PathFinder/PathFinderURLProvider.py
This PR updates PathFinderURLProvider to use the new [URLGetter superclass](https://github.com/autopkg/autopkg/wiki/Downloading-from-the-Internet-in-Custom-Processors), which should ease the transition to Python 3 and AutoPkg 2.
The Path Finder recipes have also been updated to handle the downloaded disk image, rather than the zip file that contained previous Path Finder versions.
Verbose run log:
https://gist.github.com/homebysix/908eb0592f8a802f57067133a60cd851
=> Use URLGetter superclass for PathFinderURLProvider, handle Path Finder disk image

Camtasia/Camtasia.download.recipe
Generic URL retrieved from:
https://www.techsmith.com/download-camtasia-mac-thankyou.html
Utilised CodeSignatureVerification updates from https://github.com/autopkg/jps3-recipes/pull/75
Removed versioning steps, as the Munki recipe will handle this and rename the .dmg file accordingly.
=> Updating to download from generic URL 

BetterZip/BetterZip.munki.recipe
`pkg_path` and `repo_subdirectory` are not valid arguments for [MunkiPkginfoMerger](https://github.com/autopkg/autopkg/wiki/Processor-MunkiPkginfoMerger).
=> Adjust MunkiPkginfoMerger arguments

BabelColor/BabelColorCTA.pkg.recipe, Pashua/Pashua.pkg.recipe
`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).
=> Adjust PkgCreator arguments

NVIDIA/NvidiaCudaDriver.download.recipe
Nvidia CUDA 10.2 (toolkit and driver) was the last release to support macOS. Details:
- https://docs.nvidia.com/cuda/archive/10.2/cuda-toolkit-release-notes/index.html#title-new-features
- https://mjtsai.com/blog/2019/11/25/nvidia-drops-cuda-support-for-macos/
- https://gizmodo.com/apple-and-nvidia-are-over-1840015246
Related: https://github.com/autopkg/novaksam-recipes/pull/68, https://github.com/autopkg/jessepeterson-recipes/pull/96
=> Deprecate Nvidia CUDA recipes

OpenSCAD/OpenSCAD.download.recipe
The URL for the appcast changed, here is the output:
```
~ autopkg run -vv OpenSCAD.pkg                                                                           
Processing OpenSCAD.pkg...
WARNING: OpenSCAD.pkg is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://openscad.github.io/appcast.xml'}}
SparkleUpdateInfoProvider: Version retrieved from appcast: 2019.05.10
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 2019.05
SparkleUpdateInfoProvider: Found URL https://files.openscad.org/OpenSCAD-2019.05.dmg
{'Output': {'url': 'https://files.openscad.org/OpenSCAD-2019.05.dmg',
'version': '2019.05'}}
URLDownloader
{'Input': {'url': …
```
=> Appcast URL change

Camtasia/Camtasia.munki.recipe
As of the 2020 releases, the Rogue Amoeba's Audio Capture Engine component they license is recommended to be installed for end users, https://support.techsmith.com/hc/en-us/articles/203727638-Camtasia-Mac-Enterprise-Install-Guidelines
May as well handle that on postinstall
=> add postinstall as per vendor docs

PathFinder/PathFinderURLProvider.py, WacomIntuosProDriver/AddExecutePermissionsToDirectories.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+

Arduino/Arduino.download.recipe, Arduino/Arduino.munki.recipe, Arduino/Arduino.pkg.recipe
Hi, @jps3 
The current Arduino download recipes downloads the legacy version.
This PR updates to get the latest from GitHub and adds in support for downloading both Intel and Apple Silicon versions. 
The Munki and Pkg recipes have also been updated to account for the changes in the download recipe. 
Output from a success full Munki run 
```
autopkg run -v /Users/paul.cossey/Documents/GitHub/AutoPkg\ Repos/jps3-recipes/Arduino/Arduino.munki.recipe 
Processing /Users/paul.cossey/Documents/GitHub/AutoPkg Repos/jps3-recipes/Arduino/Arduino.munki.recipe...
WARNING: /Users/paul.cossey/Documents/GitHub/AutoPkg Repos/jps3-recipes/Arduino/Arduino.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: …
```
=> Update Arduino Recipes

Arduino/Arduino.download.recipe, Arduino/Arduino.pkg.recipe
The last update to the Arduino download recipe doesn't actually use the %ARCH_TYPE% input variable, so it cannot be overridden to allow one to download the ARM flavor.
I also simplified the Arduino .pkg recipe.
=> Arduino Patches
